language: r

os:
 - linux
 - osx

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: false

sudo: required

notifications:
 email:
  on_failure: change
