language: r

os:
 - linux
 - osx

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false

sudo: required

notifications:
 email:
  on_failure: change
