language: r

os:
 - linux
# - osx

r_packages:
  - covr
  - testthat

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then Rscript -e 'covr::codecov()'; fi

warnings_are_errors: false

sudo: required

notifications:
 email:
  on_failure: change
